name: int-ambulatorio
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.25.2
  - matplotlib=3.7.2
  - numpy=1.25.2
  - openpyxl=3.0.10
  - pandas=2.0.3
  - python=3.11.5
  - seaborn=0.12.2
  - pip:
      - ecoport==0.0.1
      - pyyaml==6.0.1
